-- THREADZ — seed categories + product catalog (14 SKUs)
-- Safe to re-run (uses ON CONFLICT)

insert into public.categories (id, name, description, sort_order)
values
  (
    'plain',
    'Plain T-Shirts',
    'Classic fit tees in premium cotton blends and interlock fabrics',
    1
  ),
  (
    'oversized',
    'Oversized T-Shirts',
    'Relaxed oversized fit in heavy jersey cotton',
    2
  )
on conflict (id) do update set
  name = excluded.name,
  description = excluded.description,
  sort_order = excluded.sort_order,
  updated_at = now();

insert into public.products (
  id,
  category_id,
  name,
  description,
  quality,
  color,
  price,
  mrp,
  image,
  category,
  gsm,
  size_s,
  size_m,
  size_l,
  size_xl,
  quantity
)
values
  (
    '1',
    'plain',
    'Charcoal Melange Plain Tee',
    'Charcoal Melange plain tee in a breathable cotton-poly blend for everyday wear.',
    '55% cotton 45% polyester 180 GSM',
    'Charcoal Melange',
    499,
    899,
    'https://raw.githubusercontent.com/shashanka2a/Threadz-App/main/assets/charcoal.jpg',
    'Plain T-Shirts',
    '180 GSM',
    8, 8, 8, 8, 32
  ),
  (
    '2',
    'plain',
    'Grey Melange Plain Tee',
    'Grey Melange plain tee in premium cotton for all-day comfort.',
    '93% cotton 7% polyester 180 GSM',
    'Grey Melange',
    499,
    899,
    'https://raw.githubusercontent.com/shashanka2a/Threadz-App/main/assets/grey.jpg',
    'Plain T-Shirts',
    '180 GSM',
    6, 6, 6, 6, 24
  ),
  (
    '3',
    'plain',
    'Cream Plain Tee',
    'Cream plain tee in premium cotton for all-day comfort.',
    '100% cotton 180 GSM',
    'Cream',
    499,
    899,
    'https://raw.githubusercontent.com/shashanka2a/Threadz-App/main/assets/cream.jpg',
    'Plain T-Shirts',
    '180 GSM',
    9, 9, 9, 9, 36
  ),
  (
    '4',
    'plain',
    'LT Green Plain Tee',
    'LT Green plain tee in premium cotton for all-day comfort.',
    '100% cotton 180 GSM',
    'LT Green',
    499,
    899,
    'https://raw.githubusercontent.com/shashanka2a/Threadz-App/main/assets/LTGreen.png',
    'Plain T-Shirts',
    '180 GSM',
    9, 9, 9, 9, 36
  ),
  (
    '5',
    'plain',
    'Plum Plain Tee',
    'Plum plain tee in premium cotton for all-day comfort.',
    '100% cotton 180 GSM',
    'Plum',
    499,
    899,
    'https://raw.githubusercontent.com/shashanka2a/Threadz-App/main/assets/plum.png',
    'Plain T-Shirts',
    '180 GSM',
    7, 7, 7, 7, 28
  ),
  (
    '6',
    'plain',
    'P.T Blue Plain Tee',
    'P.T Blue plain tee in premium cotton for all-day comfort.',
    '100% cotton 180 GSM',
    'P.T Blue',
    499,
    899,
    'https://raw.githubusercontent.com/shashanka2a/Threadz-App/main/assets/PTBlue.png',
    'Plain T-Shirts',
    '180 GSM',
    8, 8, 8, 8, 32
  ),
  (
    '7',
    'plain',
    'Burgundy Plain Tee',
    'Burgundy plain tee in heavier 200 GSM cotton for extra durability.',
    '100% cotton 200 GSM',
    'Burgundy',
    599,
    999,
    'https://raw.githubusercontent.com/shashanka2a/Threadz-App/main/assets/Burgandry.jpg',
    'Plain T-Shirts',
    '200 GSM',
    7, 7, 7, 7, 28
  ),
  (
    '8',
    'plain',
    'Dusty Rose Plain Tee',
    'Dusty Rose plain tee in heavier 200 GSM cotton for extra durability.',
    '100% cotton 200 GSM',
    'Dusty Rose',
    599,
    999,
    'https://raw.githubusercontent.com/shashanka2a/Threadz-App/main/assets/dustyRose.jpg',
    'Plain T-Shirts',
    '200 GSM',
    8, 8, 8, 8, 32
  ),
  (
    '9',
    'plain',
    'Brown Plain Tee',
    'Brown plain tee in heavier 200 GSM cotton for extra durability.',
    '100% cotton 200 GSM',
    'Brown',
    599,
    999,
    'https://raw.githubusercontent.com/shashanka2a/Threadz-App/main/assets/brown.png',
    'Plain T-Shirts',
    '200 GSM',
    5, 5, 4, 5, 19
  ),
  (
    '10',
    'oversized',
    'Steel Grey Oversized Tee',
    'Steel Grey oversized tee in heavy jersey cotton with a relaxed streetwear fit.',
    '100% cotton Heavy Jersey 220 GSM',
    'Steel Grey',
    599,
    1299,
    'https://raw.githubusercontent.com/shashanka2a/Threadz-App/main/assets/steelGrey.jpg',
    'Oversized T-Shirts',
    '220 GSM',
    6, 6, 6, 6, 24
  ),
  (
    '11',
    'oversized',
    'Wild Ginger Oversized Tee',
    'Wild Ginger oversized tee in heavy jersey cotton with a relaxed streetwear fit.',
    '100% cotton Heavy Jersey 220 GSM',
    'Wild Ginger',
    599,
    1299,
    'https://raw.githubusercontent.com/shashanka2a/Threadz-App/main/assets/wildGinger.jpg',
    'Oversized T-Shirts',
    '220 GSM',
    5, 6, 6, 6, 23
  ),
  (
    '12',
    'oversized',
    'Moss Green Oversized Tee',
    'Moss Green oversized tee in heavy jersey cotton with a relaxed streetwear fit.',
    '100% cotton Heavy Jersey 220 GSM',
    'Moss Green',
    599,
    1299,
    'https://raw.githubusercontent.com/shashanka2a/Threadz-App/main/assets/mossGreen.jpg',
    'Oversized T-Shirts',
    '220 GSM',
    6, 6, 6, 6, 24
  ),
  (
    '13',
    'oversized',
    'Park Petrol Oversized Tee',
    'Park Petrol oversized tee in heavy jersey cotton with a relaxed streetwear fit.',
    '100% cotton Heavy Jersey 220 GSM',
    'Park Petrol',
    599,
    1299,
    'https://raw.githubusercontent.com/shashanka2a/Threadz-App/main/assets/parkPetrol.png',
    'Oversized T-Shirts',
    '220 GSM',
    6, 6, 6, 6, 24
  ),
  (
    '14',
    'plain',
    'Pink Plain Tee',
    'Pink plain tee in soft interlock cotton for a smooth, structured feel.',
    '100% cotton Interlock 220 GSM',
    'Pink',
    599,
    1199,
    'https://raw.githubusercontent.com/shashanka2a/Threadz-App/main/assets/pink.jpg',
    'Plain T-Shirts',
    '220 GSM',
    12, 12, 12, 11, 47
  )
on conflict (id) do update set
  category_id = excluded.category_id,
  name = excluded.name,
  description = excluded.description,
  quality = excluded.quality,
  color = excluded.color,
  price = excluded.price,
  mrp = excluded.mrp,
  image = excluded.image,
  category = excluded.category,
  gsm = excluded.gsm,
  size_s = excluded.size_s,
  size_m = excluded.size_m,
  size_l = excluded.size_l,
  size_xl = excluded.size_xl,
  quantity = excluded.quantity,
  is_active = true,
  updated_at = now();
